### ISSUE TITLE
Translate in Italian language!

### ISSUE THREAD

**Issue by Denisov21** [DH3ALEJANDRO/Show-Recently-Used#1]

**Comment by DH3ALEJANDRO** [comment]
please translate:

Spanish | Italian
------------ | -------------
Mostrar Archivos Utilizados Recientemente | ...
Reciente | ...
Reabrir Archivo Cerrado | ...
Borrar Lista | ...
No guardar Historial Hasta Reiniciar Brackets | ...
Añadir al Historial cuando el archivo está trabajando | ...
Su navegador no soporta el almacenamiento local | ...
Número de entradas a mostrar | ...
excluir archivos | ...
guardar | ...

**Comment by Denisov21** [comment]
Spanish | Italian
------------ | -------------
Mostrar Archivos Utilizados Recientemente | Mostra file utilizzati di recente
Reciente | Recente
Reabrir Archivo Cerrado 	| Riapri archivio chiuso
Borrar Lista | Cancella elenco
No guardar Historial Hasta Reiniciar Brackets 	| Non salvare la cronologia fino al riavvio di Brackets
Añadir al Historial cuando el archivo está trabajando | Aggiungere alla storia quando il file è in funzione
Su navegador no soporta el almacenamiento local | Il tuo browser non supporta storage locale
Número de entradas a mostrar | Numero di voci da visualizzare
excluir archivos | escludere file
guardar | salvare

**Comment by DH3ALEJANDRO** [comment]
missing one: 


English | Italian
------------ | -------------
Add a menu at the top of the editor with a list of all the files shown recently | ...

**Comment by Denisov21** [comment]
English | Italian
------------ | -------------
Add a menu at the top of the editor with a list of all the files shown recently | Aggiungere un menu in cima all'editor con un elenco di tutti i file recentemente dimostrati

**Comment by DH3ALEJANDRO** [comment]
there!, now update :)
