### ISSUE TITLE
I can't see the bar...

### ISSUE THREAD

**Issue by PandawanFr** [DH3ALEJANDRO/Show-Recently-Used#3]
The menu bar isn't here, even though I have the Recent tab, I don't have the bar with all recent files. 
I'm on Brackets latest version (I think it's 1.2), Mac OS X Yosemite

**Comment by DH3ALEJANDRO** [comment]
please i want a screenshot.

**Comment by PandawanFr** [comment]
I'm stupid, the extension wasn't active... Sorry
